Running test: should_fail
FAIL
Running test: should_pass
PASS
Running test: throws_error
ERROR

*** Results ***
** Test case 'should_fail': FAIL
In test , line 6: 
42 != 43

** Test case 'should_pass': PASS
** Test case 'throws_error': ERROR
Uncaught exception in test throws_error: 
errorrr!

*** Summary ***
Out of 3 tests run:
1 failure(s), 1 error(s)
